package Adventures.Players;

/**
 * Created by Aaron Fisher on 4/29/2017.
 */
public enum Occupation {
    Cobbler,
    Gardener,
    Wordsmith,
    Priest,
    Paladin,
    Knight,
    Barbarian,
    Peasant,
    Leper,
    Prestidigitarian,
    Dwarf,
    Gazebo,
    Gastroenterologist,
    Speedrunner,
    Spelunker,
    Canadian,
    Gargoyle,
    Pikachu,
    Elephant,
//    Ninja_Turtle,
    Federalist,
    Spambot,
//    Menace_to_Society,
    Dietician,
    Pleb,
    Detective,
    Chaperone,
    Quizmaster,
    Presbyterian,
    Cowboy,
    Paraglider,
    Rockette,
//    Chess_Boxer,
    Labradoodle,
    Thief,
    Rogue,
    Defenestrator,
    Cleric,
    Hustler,
    Badass,
    Warrior,
    Hunter,
    Druid,
    Shaman,
    Roommate,
    Cruciverbalist,
    Peon,
    Monk,
    Knave,
    Gumshoe;
}
